'''
นี่คือโปรแกรมแรกของเรา
'''
# This code is for testing the types of various operations in Python.   
print("Hello, World!")
print("10"+"10")
print(type('Hello, World!'))
print(type(10))
print(type(10.5))
print(type(False))
print(type(1j))
print(type(10+3.5))
print(type([1, 2, 3]))
print(type((1, 2, 3)))
print(type({'name': 'John', 'age': 30}))
print(type({1, 2, 3}))
print(type(None))
print(type(print))
print(type(int))
print(type(str))
print(type(list))
print(type(tuple))
print(type(dict))
print(type(set))
print(type(bool))
print(type(float))
print(type(complex))
print(type(type(10)))
print(type(type('Hello, World!')))
print("10"+"5")